### PR TITLE
Migrate from godep to go modules

### PR DESCRIPTION
**Pull request by kampka**
This PR migrates the dependency management from `go dep` to the new go modules as described in https://github.com/golang/go/wiki/Modules

### CODE REVIEW

**Comment by babarot** [comment]
@kampka 

Please modify .travis.yml also to fix CI failing.

**Comment by kampka** [comment]
Indeed, forgot about that.
Should be fixed now.

**Comment by b4b4r07** [comment]
Thank you. Wait for the updates.

**Review by babarot — APPROVED** [review]
LGTM

**Pull request merged**
